apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: consumer
  labels:
    app: kafka-consumer
spec:
  selector:
    matchLabels:
      app: kafka-consumer
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      hostname: kafka-consumer
      containers:
        - name: grpc-client
          image: mruiz01329/consumer_kafka
          env:
          - name: BROKER_ADDR
            value: my-cluster-kafka-bootstrap.kafka


---